export const GET_LIST_OF_CITIES = 'GET_LIST_OF_CITIES';
export const CLEAR_CITIES_LIST = 'CLEAR_CITIES_LIST';

export const SET_LOCATION_START = 'SET_LOCATION_START';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_LOCATION_FAIL = 'SET_LOCATION_FAIL';

export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
